create table
  public.global_inventory (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    num_green_potions integer null default 0,
    num_green_ml integer null default 0,
    gold integer null default 100,
    num_red_potions integer null default 0,
    num_red_ml integer null default 0,
    num_blue_potions integer null default 0,
    num_blue_ml integer null default 0,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;